#!/bin/bash

source "`dirname $0`/init.sh"

ARGS=path
DESCRIPTION="Returns success if the path exists in the Dropbox."

test -z "$1" && dbx-exit-on-usage "$ARGS" "$DESCRIPTION"

FULL_PATH=`realpath -m "/$1"`
DIRNAME=`dirname "$FULL_PATH"`

test "$FULL_PATH" = "/" && exit 0

LISTING=`dbxcli ls -l "$DIRNAME"` || \
    dbx-exit-on-error "Cannot access: $DIRNAME"

echo "$LISTING" | \
    grep -qE "^-[[:blank:]]+-[[:blank:]]+-[[:blank:]]+$FULL_PATH[[:blank:]]+\$" && \
    exit 0

dbx-exit-on-error "Not a directory: $FULL_PATH"
