#!/bin/bash

source "`dirname $0`/init.sh"

dbx-parse-options "$@"
shift $((OPTIND-1))

# Unlikely, but who knows...:
if test "$DBX_HOME" = /; then
    echo "$PWD"
    exit
fi

DBX_PWD=${PWD##$DBX_HOME}
test "$DBX_PWD" = "$PWD" && \
    dbx-exit-on-error "Current directory not in \$DBX_HOME (\`$DBX_HOME')"

if test -z "$DBX_PWD"; then
    echo "/"
    exit
fi

echo "$DBX_PWD"
