#!/bin/bash

function dbx-cd {
    test -z "$1" && RELATIVE_PATH="/" || RELATIVE_PATH="$1"
    OUT=`dbx-make-local-dir "$RELATIVE_PATH"` && \
	cd "$OUT" || \
	    echo "$OUT" >&2
}

test "$0" = "$BASH_SOURCE" && \
    cat <<EOF
Source this script to get \`dbx-cd':

source "$0"
EOF
