#!/bin/bash

source "`dirname $0`/init.sh"

NON_OPTION_ARGS="PATH"

DESCRIPTION=$(cat <<EOF
Download PATH from the Dropbox. If PATH is a directory, downloads its
contents recursively. Dropbox is case insensitive to file names. If a
file already exists locally, the case of its name is preserved.
EOF
	   )

dbx-parse-options "$@"
shift $((OPTIND-1))

P="$1"
shift || dbx-exit-on-missing-args

shopt -s nocasematch

DBX_PATH=`dbx-path "$P"`
dbxcli ls -Rl "$DBX_PATH" | \
    tail -n +2 | \
    while read LINE; do
	if [[ $LINE =~ ^-[[:blank:]]+-[[:blank:]]+-[[:blank:]]+ ]];
	then
	    M=${BASH_REMATCH[0]}
	    DBX_FILE="${LINE##$M}"
	    LOCAL_FILE=`dbx-local-path "$DBX_FILE"`
	    echo "Creating local directory: $LOCAL_FILE"
	    mkdir -p "$LOCAL_FILE"
	elif [[ $LINE =~ ^[^/]+ ]]; then
	    M=${BASH_REMATCH[0]}
	    DBX_FILE="${LINE##$M}"
	    LOCAL_FILE=`dbx-local-path "$DBX_FILE"`
	    echo "$DBX_FILE"
	    dbxcli get "$DBX_FILE" "$LOCAL_FILE" || exit
	fi
    done
