#!/bin/bash

source "`dirname $0`/init.sh"

OPTIONS[r]="recursive removal"
NON_OPTION_ARGS="PATH"
DESCRIPTION=$(cat <<EOF
Remove PATH from the Dropbox. If PATH is a directory, remove its
contents recursively.
EOF
           )

parse-options "$@"
shift $((OPTIND-1))

REQUESTED_PATH="$1"
shift || exit-on-missing-args

DBX_PATH=`dbx-path "$REQUESTED_PATH"`
dbx-test-dir "$DBX_PATH" 2>/dev/null && PATH_IS_DIR=y

function test-is-non-empty-directory {
    test -v PATH_IS_DIR || return 1
    C=$(dbxcli ls -l "$DBX_PATH" | wc -l)
    test $C -gt 1
}

if ! test-option-enabled r; then
    test-is-non-empty-directory && \
        exit-on-error "Directory is not empty: $DBX_PATH"
fi

test -v PATH_IS_DIR && TYPE=Directory || TYPE=File
echo "$TYPE to remove: $DBX_PATH"
read -r -p "Proceed with removal? [y/N] " RESPONSE
test "${RESPONSE,,}" = y || exit-on-cancelled

test-option-enabled r && O=-f || O=
dbxcli rm $O "$DBX_PATH" || \
    exit-on-error "Could not remove from Dropbox: $DBX_PATH"

LOCAL_PATH=`local-path "$DBX_PATH"`
if test -a "$LOCAL_PATH"; then
    test-option-enabled r && O=-r || O=
    rm $O "$LOCAL_PATH" || \
        exit-on-error "Could not remove locally: $LOCAL_PATH"
fi
