#!/bin/bash

source "`dirname $0`/init.sh"

ARGS=path
DESCRIPTION="If not existing, creates a local directory corresponding to the path.
Enters that directory."

test -z "$1" && dbx-exit-on-usage "$ARGS" "$DESCRIPTION"

FULL_PATH=`realpath -m "/$1"`
dbx-test-dir "$FULL_PATH"

LOCAL_PATH="DBX_HOME$FULL_PATH"
mkdir -p "$LOCAL_PATH" || \
    dbx-exit-on-error "Cannot create directory: $FULL_PATH"

cd "$LOCAL_PATH" || \
    dbx-exit-on-error "Cannot enter directory: $FULL_PATH"
