#!/bin/bash

source "`dirname $0`/init.sh"

NON_OPTION_ARGS=PATH
DESCRIPTION=$(cat <<EOF
If not existing, creates a local directory corresponding to the
path on Dropbox, relative to the current location. Outputs that
directory.
EOF
	   )

dbx-parse-options "$@"
shift $((OPTIND-1))

test -z "$1" && dbx-exit-on-missing-args

DBX_PATH=`dbx-path "$1"` || exit
dbx-test-dir "$DBX_PATH" || exit

LOCAL_PATH="$DBX_HOME$DBX_PATH"
mkdir -p "$LOCAL_PATH" || \
    dbx-exit-on-error "Cannot create local directory: $LOCAL_PATH"

echo "$LOCAL_PATH"
