#!/bin/bash

source "`dirname $0`/init.sh"

OPTIONS[l]="detailed listing"
OPTIONS[R]="recursive listing"

NON_OPTION_ARGS="[PATH]"

DESCRIPTION=$(cat <<EOF
List information about the current Dropbox directory, or if
specified, about PATH.
EOF
	   )

dbx-parse-options "$@"
shift $((OPTIND-1))

DBX_PATH=`dbx-path "$1"`

test -n "$ENABLED_OPTIONS" && S=-$ENABLED_OPTIONS || S=""
dbx-test-option-enabled l && { dbxcli ls $S "$DBX_PATH"; exit; }

function dbx-relative-path-from-match {
    P=`dbx-path-from-match "$1"`
    if test "$DBX_PATH" != /; then
	C=${#DBX_PATH}
	P="${P:$C}"
    fi
    echo ${P:1}
}

shopt -s nocasematch

dbxcli ls -l $S "$DBX_PATH" | \
    tail -n +2 | \
    while read LINE; do
	if [[ $LINE =~ ^-[[:blank:]]+-[[:blank:]]+-[[:blank:]]+ ]];
	then
	    P="`dbx-relative-path-from-match`/"
	elif [[ $LINE =~ ^[^/]+ ]]; then
	    P=`dbx-relative-path-from-match`
	fi
	test "$P" = / || echo $P
    done

