#!/bin/bash

source "`dirname $0`/init.sh"

DESCRIPTION=$(cat <<EOF
Clears empty directories in \$DBX_HOME.
EOF
           )
parse-options "$@"
shift $((OPTIND-1))

cd "$DBX_HOME"
find -type d | tac | while read DIR; do
    rmdir "$DIR" 2>/dev/null && \
        echo "Removed empty directory ${DIR##./}"
done
