#!/bin/bash

source "`dirname $0`/init.sh"

ARGS=PATH
DESCRIPTION="Return success if the path exists in the Dropbox."

parse-options "$@"
shift $((OPTIND-1))

test -z "$1" && exit-on-missing-args

ABSOLUTE_PATH=`realpath -m "/$1"`

LISTING=`dbxcli ls "$ABSOLUTE_PATH"` || \
    exit-on-error "Cannot access on Dropbox: $ABSOLUTE_PATH"
