#!/bin/bash

source "`dirname $0`/init.sh"

OPTIONS[l]="detailed listing"
OPTIONS[R]="recursive listing"

NON_OPTION_ARGS="[PATH]"

DESCRIPTION=$(cat <<EOF
List information about the current Dropbox directory, or if
specified, about PATH.
EOF
	   )

dbx-parse-options "$@"
shift $((OPTIND-1))

REQUESTED_PATH=$1
DBX_PATH=`dbx-path "$1"`

function dbx-relative-path-from-match {
    MATCH=$1
    ISDIR=$2
    P="${LINE##$MATCH}"
    if test "${P,,}" == "${DBX_PATH,,}"; then
	test "$ISDIR" = yes && echo . || echo "$REQUESTED_PATH"
	exit
    fi
    if test "$DBX_PATH" != /; then
	C=${#DBX_PATH}
	P="${P:$C}"
    fi
    P="${P:1}"
    test "$P" = / && P=""
    echo $P
}

function dbx-print-path-line {
    LINE="$1"
    MATCH="$2"
    ISDIR=$3
    RELPATH=`dbx-relative-path-from-match "$MATCH" $ISDIR`
    test -v LONG && echo -n "$MATCH"
    echo -n "$RELPATH"
    test "$RELPATH" != . && test "$ISDIR" = yes && echo -n /
    echo
}

shopt -s nocasematch

dbx-test-option-enabled l && LONG=yes
dbx-test-option-enabled R && O=-R

dbxcli ls -l $O "$DBX_PATH" | \
    while read LINE; do
	if [[ $LINE =~ ^Revision ]]; then
	    # Heading
	    test -v LONG && echo "$LINE"
	elif [[ $LINE =~ ^-[[:blank:]]+-[[:blank:]]+-[[:blank:]]+ ]];
	then
	    # Directory
	    dbx-print-path-line "$LINE" "${BASH_REMATCH[0]}" yes
	elif [[ $LINE =~ ^[^/]+ ]]; then
	    # Regular file
	    dbx-print-path-line "$LINE" "${BASH_REMATCH[0]}"
	fi
    done
