#!/bin/bash

source "`dirname $0`/init.sh"

NON_OPTION_ARGS=PATH
DESCRIPTION="Return success if the path exists in the Dropbox and is a directory."

parse_options "$@"

test -z "$1" && dbx-exit-on-missing-args

ABSOLUTE_PATH=`realpath -m "/$1"`
DIRNAME=`dirname "$ABSOLUTE_PATH"`

test "$ABSOLUTE_PATH" = "/" && exit 0

LISTING=`dbxcli ls -l "$DIRNAME"` || \
    dbx-exit-on-error "Cannot access: $DIRNAME"

echo "$LISTING" | \
    grep -qE "^-[[:blank:]]+-[[:blank:]]+-[[:blank:]]+$ABSOLUTE_PATH[[:blank:]]+\$" && \
    exit 0

dbx-exit-on-error "Not a Dropbox directory: $ABSOLUTE_PATH"
