#!/bin/bash

source "`dirname $0`/init.sh"

NON_OPTION_ARGS="PATH"

DESCRIPTION=$(cat <<EOF
Download PATH from the Dropbox. If PATH is a directory, downloads its
contents recursively. Dropbox is case insensitive to file names. If a
file already exists locally, the case of its name is preserved.
EOF
	   )

dbx-parse-options "$@"
shift $((OPTIND-1))

P="$1"
shift || dbx-exit-on-missing-args

shopt -s nocasematch

function dbx-path-from-match {
    M=${BASH_REMATCH[0]}
    C=${#M}
    echo ${LINE:$C}
}

dbx-ls -Rl "$P" | \
    tail -n +2 | \
    while read LINE; do
	if [[ $LINE =~ ^-[[:blank:]]+-[[:blank:]]+-[[:blank:]]+ ]];
	then
	    DBX_PATH=`dbx-path-from-match`
	    LOCAL_PATH=`dbx-local-path "$DBX_PATH"`
	    echo "Creating local directory: $LOCAL_PATH"
	    mkdir -p "$LOCAL_PATH"
	elif [[ $LINE =~ ^[^/]+ ]]; then
	    DBX_PATH=`dbx-path-from-match`
	    LOCAL_PATH=`dbx-local-path "$DBX_PATH"`
	    echo "$DBX_PATH"
	    dbxcli get "$DBX_PATH" "$LOCAL_PATH" || exit
	fi
    done
